name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  test_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.workspace }}/go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -bench '.' ./... -benchtime=100ms
  

  test_macos:
    name: macOS
    runs-on: macos-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.workspace }}/go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -bench '.' ./... -benchtime=100ms


  test_windows:
    name: Windows
    runs-on: windows-2019
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.workspace }}/go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -bench '.' -benchtime=100ms ./...

